
import Head from 'next/head'

export default function Blog() {
    return (
      <>
        <Head>
          <title>About Us</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <h1 className='px-6 py-6 text-4xl font-bold text-center'>About Page</h1>
        </main>
      </>
    )
  }