import Head from 'next/head'
import Form from '@/components/form'

export default function Raffle() {
    return (
      <>
        <Head>
          <title>Conduct Raffle</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <h1 className='px-6 py-6 text-4xl font-bold text-center'>Conduct Raffle</h1>
         
        </main>  
      </>
    )
  }