import Head from "next/head";
import Form from "@/components/raffleForm";
import dynamic from "next/dynamic";
import { useState } from "react";
import RaffleForm from "@/components/raffleForm";
const App = dynamic(
  () => {
    return import("../pages/Web3Auth");
  },
  { ssr: false }
);

export default function Raffle() {
  const [address, setAddress] = useState<string[]>([]);
  function callback(address: string[]) {
    setAddress(address);
  }
  return (
    <>
      <Head>
        <title>Conduct Raffle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="m-2 text-center">
          <App callback={callback} />
        </div>
        {address.length > 0 ? (
          <div className="flex flex-wrap justify-center m-4">
            <RaffleForm />
          </div>
        ) : null}
      </main>
    </>
  );
}
