import Head from "next/head";

import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Card from "@/components/card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  let cards: JSX.Element[] = [];
  function generateCards() {
    for (let i = 0; i < 6; i++) {
      cards.push(
        <div className="m-2">
          <Card key={i} />
        </div>
      );
    }
  }
  generateCards();

  const cardSection = (body: any) => {
    return <div className="flex flex-wrap justify-center">{body}</div>;
  };

  return (
    <>
      <Head>
        <title>Merchant Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="px-6 py-6 text-4xl font-bold text-center">
          All Minted NFTs
        </h1>

        {cardSection(cards)}
      </main>
    </>
  );
}
